kind: Pod
apiVersion: v1
metadata:
  name: http-server-pod
  namespace: cmengdi1
spec:
  # [OPTIONAL]
  # User ID of username provided in PersistentVolumeClaim
  securityContext:
    runAsUser: 2051813
  volumes:
    - name: http-server-storage
      persistentVolumeClaim:
        # Name of PersistentVolumeClaim
        claimName: nfs-test-claim
  containers:
    - name: http-server-container
      image: bitnami/nginx:latest
      env:
      - name: USER
        value: "cmengdi"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: http-server-storage